- name: Run the front container
  docker_container:
    name: httpd
    image: royerbantoine/tp-devops-front:1.0
    recreate: true
    pull: true
    ports:
      - "8083:80"
    networks:
      - name: app-network
