version: '3.7'

services:
    backend:
        container_name: back
        build: ./BACK/simple-api-student-main
        networks:
            - app-network  # Associate this service with the "app-network" network
        depends_on:
            - database  # Wait for the "database" service to be ready before starting

    database:
        container_name: db
        build: .
        networks:
            - app-network  # Associate this service with the "app-network" network
        volumes:
            - db-volume:/var/lib/postgresql/data  # Mount the "db-volume" volume into the PostgreSQL container

    httpd:
        container_name: front
        build: ./FRONT
        ports:
            - "80:80"  # Map port 80 of the HTTPD container to port 80 of the host
        networks:
            - app-network  # Associate this service with the "app-network" network
        depends_on:
            - backend  # Wait for the "backend" service to be ready before starting

volumes:
    db-volume:

networks:
    app-network:  # Defines a network named "app-network" for communication between services
