version: '3.7'

services:
  backend:
    build: ./simple-api
    container_name: my-api
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - database

  database:
    build: ./database
    container_name: my-db
    networks:
      - my-network
    volumes:
      - db-volume:/var/lib/postgresql/data

  httpd:
    build: ./http-server
    ports:
      - "8082:80"
    networks:
      - my-network
    depends_on:
      - front

  front:
    build: ./devops-front
    container_name: my-front
    networks:
      - my-network
    ports:
      - "8083:80"
    depends_on:
      - backend

volumes:
  db-volume:

networks:
  my-network:
