# Ansible Configuration File (all.yml)
all:
  # Global variables for all host groups
  vars:
    ansible_user: centos  # SSH user to connect to hosts
    ansible_ssh_private_key_file: /home/antoine/Documents/EPF MIN/DevOps/TP3/id_rsa  # Path to the SSH private key to use for connections

  # Definition of host groups and their members
  children:
    prod:  # Host group named "prod"
      hosts: antoine.royer--bournelle.takima.cloud  # List of hosts belonging to the "prod" group