name: CI devops 2023

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout your GitHub code
        uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3  # Use the appropriate version of actions/setup-java
        with:
          java-version: 17  # Specify the JDK version you want to use
          distribution: 'adopt'  # Specify the distribution (e.g., 'adopt', 'adopt-lts', etc.)


      - name: Build and test with Maven
        run: mvn clean verify  # Replace with your actual build and test command
